# Generated by Django 3.1.2 on 2020-10-26 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('our_web_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='modeltouse',
            new_name='UserModel',
        ),
    ]
